return {
    Id = "Combat",
    Label = "Combat",
    Icon = "target",
    Bookmarked = false,
    RuntimeModule = "runtime/Combat.lua",
    Sections = {
        {
            Title = "Murder",
            Icon = "target",
            Controls = {
                { Kind = "Toggle", Setting = "MurderKillAura", Id = "murder_kill_aura", Label = "Kill Aura", Description = "Automatically attacks a valid target inside the aura radius.", Default = false },
                { Kind = "Slider", Setting = "MurderAuraRadius", Id = "murder_aura_radius", Label = "Aura Radius", Min = 4, Max = 25, Default = 12, Step = 1 },
                { Kind = "Slider", Setting = "MurderAttackDelay", Id = "murder_attack_delay", Label = "Attack Delay", Min = 0.05, Max = 1, Default = 0.15, Step = 0.05 },
                { Kind = "Dropdown", Setting = "MurderTargetPriority", Id = "murder_target_priority", Label = "Target Priority", Options = { "Nearest", "Sheriff First" }, Default = "Nearest" },
                { Kind = "Toggle", Setting = "MurderAutoEquipKnife", Id = "murder_auto_equip", Label = "Auto Equip Knife", Description = "Keeps the Knife equipped while you are the Murderer.", Default = false },
                { Kind = "Button", Setting = "MurderEquipKnife", Id = "murder_equip_knife", Label = "Equip Knife", ButtonText = "Equip" },
                { Kind = "Button", Setting = "MurderKillNearest", Id = "murder_kill_nearest", Label = "Kill Nearest", Description = "Blink-stabs the nearest alive target and returns to your position.", ButtonText = "Kill" },
                { Kind = "Button", Setting = "MurderKillSheriff", Id = "murder_kill_sheriff", Label = "Kill Sheriff", Description = "Targets the Sheriff or current Hero carrying the Gun.", ButtonText = "Kill" },
                { Kind = "Button", Setting = "MurderKillAll", Id = "murder_kill_all", Label = "Kill All", Description = "Sequentially attacks every alive non-Murderer target.", ButtonText = "Kill All" },
            },
        },
        {
            Title = "Sheriff",
            Icon = "target",
            Controls = {
                { Kind = "Toggle", Setting = "SheriffPerfectShots", Id = "sheriff_perfect_shots", Label = "Perfect Shots", Description = "Any manual Gun shot also sends a guaranteed shot to the Murderer.", Default = false },
                { Kind = "Button", Setting = "SheriffShootMurderer", Id = "sheriff_shoot_murderer", Label = "Shoot Murderer", Description = "Equips the Gun and fires directly at the current Murderer.", ButtonText = "Shoot" },
                { Kind = "Toggle", Setting = "SheriffAutoShootMurderer", Id = "sheriff_auto_shoot", Label = "Auto Shoot Murderer", Description = "When the Murderer is visible, pulls the Gun from Backpack and fires automatically.", Default = false },
                { Kind = "Slider", Setting = "SheriffShootCooldown", Id = "sheriff_shoot_cooldown", Label = "Auto Shoot Cooldown", Min = 0.4, Max = 2, Default = 1.1, Step = 0.1 },
                { Kind = "Dropdown", Setting = "SheriffTargetPart", Id = "sheriff_target_part", Label = "Target Part", Options = { "HumanoidRootPart", "Head", "UpperTorso" }, Default = "HumanoidRootPart" },
                { Kind = "Slider", Setting = "SheriffPrediction", Id = "sheriff_prediction", Label = "Prediction", Min = 0, Max = 0.35, Default = 0.08, Step = 0.01 },
                { Kind = "Toggle", Setting = "SheriffIgnoreWalls", Id = "sheriff_ignore_walls", Label = "Ignore Walls", Description = "Off by default: Auto Shoot requires direct line of sight.", Default = false },
                { Kind = "Toggle", Setting = "SheriffAutoEquipGun", Id = "sheriff_auto_equip", Label = "Auto Equip Gun", Description = "Automatically equips the Gun when it enters your Backpack.", Default = false },
                { Kind = "Button", Setting = "SheriffEquipGun", Id = "sheriff_equip_gun", Label = "Equip Gun", ButtonText = "Equip" },
                { Kind = "Toggle", Setting = "SheriffAutoGrabGun", Id = "sheriff_auto_grab", Label = "Auto Grab Dropped Gun", Description = "Attempts to collect GunDrop without moving or changing your CFrame.", Default = false },
                { Kind = "Button", Setting = "SheriffGrabGunNow", Id = "sheriff_grab_now", Label = "Grab Dropped Gun Now", Description = "Remote pickup attempt only; your character stays in place.", ButtonText = "Grab" },
            },
        },
        {
            Title = "Utils",
            Icon = "shield",
            Controls = {
                { Kind = "Toggle", Setting = "UtilsAutoEvadeMurderer", Id = "utils_auto_evade", Label = "Auto Evade Murderer", Description = "Moves away when the Murderer enters the danger radius.", Default = false },
                { Kind = "Slider", Setting = "UtilsDangerRadius", Id = "utils_danger_radius", Label = "Danger Radius", Min = 5, Max = 40, Default = 15, Step = 1 },
                { Kind = "Slider", Setting = "UtilsEvadeDistance", Id = "utils_evade_distance", Label = "Evade Distance", Min = 10, Max = 50, Default = 30, Step = 1 },
                { Kind = "Toggle", Setting = "UtilsHitboxExpander", Id = "utils_hitbox", Label = "Hitbox Expander", Description = "Locally expands HumanoidRootPart for the selected combat target.", Default = false },
                { Kind = "Slider", Setting = "UtilsHitboxSize", Id = "utils_hitbox_size", Label = "Hitbox Size", Min = 2, Max = 15, Default = 6, Step = 1 },
                { Kind = "Dropdown", Setting = "UtilsHitboxTarget", Id = "utils_hitbox_target", Label = "Hitbox Target", Options = { "Murderer", "Sheriff", "Everyone" }, Default = "Murderer" },
            },
        },
    },
}
